version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: WSU_2024_improved_w_survey
    restart: always
    volumes:
      - ./build/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=work_order_pro
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  backend:
    image: sakahle/work-order-pro-microservice:v1
    container_name: work-order-pro-service
    restart: always
    depends_on:
      - mariadb
    environment:
      - DATABASE_DRIVER=org.mariadb.jdbc.Driver
      - DATABASE_PASSWORD=password
      - DATABASE_URL=jdbc:mariadb://WSU_2024_improved_w_survey:3306/work_order_pro
      - DATABASE_USERNAME=user
      - SERVER_CONTEXT_PATH=/work-order-pro-service
      - SERVER_PORT=8080
    ports:
      - 8080:8080